#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

import math

max_num = 100000

def getTriangles():
    output = []
    for x in range(max_num):
        output.append(x*(x+1)/2)
    return output

def isPentHex(num):
    if not ((1/6)*(math.sqrt(24*num+1)+1)).is_integer(): #isPent
        return False
    if not ((math.sqrt(8*num+1)+1)/4).is_integer():
        return False
    return True

tris = getTriangles()

for num in tris:
    if isPentHex(num):
        print(num)